// Track 5 — Quantum Phase Estimation (Quantum Radar) Level Definitions
// 10 Progressive learning levels with real QPE simulation, multi-signal radar hunting,
// precision choices (2, 3, 4 bits), probabilistic sampling, and resource constraints.

import type { LevelDefinition } from '../types';
import type {
  QuantumRadarLevelConfig,
  PhaseLevelDefinition,
} from '../engines/phaseEstimationEngine';

export interface PhaseLevelConfig extends LevelDefinition, QuantumRadarLevelConfig {
  phaseLevel: PhaseLevelDefinition;
}

export const TRACK_5_LEVELS: PhaseLevelConfig[] = [
  // LEVEL 1: FIND THE SIGNAL
  {
    id: 't5_l1',
    trackId: 'phase-estimation',
    trackNumber: 5,
    levelNumber: 1,
    title: 'Find the Signal',
    subtitle: 'High-Band Signal Detection (φ = 0.500)',
    description: 'Two unknown signal sources are detected by the quantum radar. Scan the radar spectrum, select the source in the upper half (0.45–0.55), and run a 2 or 3-bit QPE experiment to estimate its eigenphase within ±0.05.',
    difficulty: 'Beginner',
    educationalConcept: 'Quantum Phase Estimation uses controlled unitary operations and an inverse QFT to reveal the unknown eigenphase φ in U|ψ⟩ = e^(2πiφ)|ψ⟩ as a measurable binary fraction.',
    hints: [
      'Click on signal S2 (Beta) on the radar display: its preliminary region is 0.45–0.55.',
      'Click "Run QPE Experiment" with 2 or 3 bits of precision to generate the measurement distribution.',
      'Notice the peak probability lands squarely on bitstring |10⟩ (or |100⟩). In binary fraction, 1/2 = 0.500.',
      'Lock onto S2 with estimated phase 0.500.',
    ],
    initialState: { selectedSignalId: null, playerPhaseEstimate: null, hasRunQPE: false },
    targetState: { targetSignalId: 'S2', truePhase: 0.5 },
    tolerance: 0.05,
    targetSignalId: 'S2',
    targetPhaseRange: [0.45, 0.55],
    targetTolerance: 0.05,
    allowedPrecisionBits: [2, 3],
    requiredPrecisionBits: 2,
    signals: [
      {
        id: 'S1',
        name: 'Alpha Beacon',
        truePhase: 0.20,
        knownRegion: '0.15–0.25',
        frequencyBand: 'S-Band',
        description: 'Low-frequency calibration carrier.',
      },
      {
        id: 'S2',
        name: 'Beta Echo',
        truePhase: 0.50,
        knownRegion: '0.45–0.55',
        frequencyBand: 'X-Band',
        description: 'High-band target beacon with eigenphase e^(iπ) = -1.',
      },
    ],
    xpReward: 250,
    starThresholds: { threeStars: 200, fourStars: 250, fiveStars: 300 },
    phaseLevel: {
      truePhase: 0.50,
      estimationQubits: 2,
      tolerance: 0.05,
      difficulty: 'Beginner',
      description: 'Find upper half signal φ = 0.500',
    },
  },

  // LEVEL 2: ONE/TWO-BIT ESTIMATE
  {
    id: 't5_l2',
    trackId: 'phase-estimation',
    trackNumber: 5,
    levelNumber: 2,
    title: 'Quarter-Turn Calibration',
    subtitle: 'Coarse 2-Bit Phase Resolution (φ = 0.250)',
    description: 'Two beacons emit orthogonal rotational signals. Locate the quarter-turn signal (phase near 0.250) and estimate its phase within ±0.04 using 2-bit QPE precision.',
    difficulty: 'Beginner',
    educationalConcept: 'With 2 estimation qubits, the computational basis states represent dyadic quarters: |00⟩ = 0.0, |01⟩ = 0.25, |10⟩ = 0.50, and |11⟩ = 0.75.',
    hints: [
      'Target signal S1 (Gamma): its phase region is near 0.20–0.30.',
      'Select S1 and execute QPE with 2 bits of precision.',
      'The histogram peaks at |01⟩. In binary fraction: 0/2 + 1/4 = 0.250.',
      'Enter 0.250 and lock the signal.',
    ],
    initialState: { selectedSignalId: null, playerPhaseEstimate: null, hasRunQPE: false },
    targetState: { targetSignalId: 'S1', truePhase: 0.25 },
    tolerance: 0.04,
    targetSignalId: 'S1',
    targetPhaseRange: [0.21, 0.29],
    targetTolerance: 0.04,
    allowedPrecisionBits: [2, 3],
    requiredPrecisionBits: 2,
    signals: [
      {
        id: 'S1',
        name: 'Gamma Pulse',
        truePhase: 0.25,
        knownRegion: '0.20–0.30',
        frequencyBand: 'C-Band',
        description: 'Target quarter-turn phase signal.',
      },
      {
        id: 'S2',
        name: 'Delta Flare',
        truePhase: 0.75,
        knownRegion: '0.70–0.80',
        frequencyBand: 'Ku-Band',
        description: 'Three-quarter turn decoy emission.',
      },
    ],
    xpReward: 300,
    starThresholds: { threeStars: 250, fourStars: 300, fiveStars: 350 },
    phaseLevel: {
      truePhase: 0.25,
      estimationQubits: 2,
      tolerance: 0.04,
      difficulty: 'Beginner',
      description: 'Quarter turn phase φ = 0.250',
    },
  },

  // LEVEL 3: TWO-BIT RADAR
  {
    id: 't5_l3',
    trackId: 'phase-estimation',
    trackNumber: 5,
    levelNumber: 3,
    title: 'Two-Bit Radar Spectrum',
    subtitle: 'Three-Quarter Turn Target (φ = 0.750)',
    description: 'Three radar contacts appear across the quantum spectrum. Locate the signal in the high three-quarter band (0.70–0.80) and estimate its phase within ±0.035.',
    difficulty: 'Intermediate',
    educationalConcept: 'Reading a multi-signal radar requires scanning each candidate, observing which one matches the mission band, and decoding its binary peak.',
    hints: [
      'Review the three signals: S1 (0.25), S2 (0.50), and S3 (0.75). The mission calls for 0.70–0.80.',
      'Select S3 (Zeta) and run the QPE experiment.',
      'The measurement readout peaks at |11⟩: 1/2 + 1/4 = 0.750.',
      'Lock onto S3 with estimated phase 0.750.',
    ],
    initialState: { selectedSignalId: null, playerPhaseEstimate: null, hasRunQPE: false },
    targetState: { targetSignalId: 'S3', truePhase: 0.75 },
    tolerance: 0.035,
    targetSignalId: 'S3',
    targetPhaseRange: [0.70, 0.80],
    targetTolerance: 0.035,
    allowedPrecisionBits: [2, 3],
    requiredPrecisionBits: 2,
    signals: [
      {
        id: 'S1',
        name: 'Epsilon Node',
        truePhase: 0.25,
        knownRegion: '0.20–0.30',
        frequencyBand: 'L-Band',
      },
      {
        id: 'S2',
        name: 'Eta Relay',
        truePhase: 0.50,
        knownRegion: '0.45–0.55',
        frequencyBand: 'S-Band',
      },
      {
        id: 'S3',
        name: 'Zeta Transmitter',
        truePhase: 0.75,
        knownRegion: '0.70–0.80',
        frequencyBand: 'X-Band',
        description: 'Mission target with phase 0.750.',
      },
    ],
    xpReward: 350,
    starThresholds: { threeStars: 300, fourStars: 350, fiveStars: 400 },
    phaseLevel: {
      truePhase: 0.75,
      estimationQubits: 2,
      tolerance: 0.035,
      difficulty: 'Intermediate',
      description: 'Three-quarter turn φ = 0.750',
    },
  },

  // LEVEL 4: THREE-BIT PRECISION
  {
    id: 't5_l4',
    trackId: 'phase-estimation',
    trackNumber: 5,
    levelNumber: 4,
    title: 'Three-Bit Precision',
    subtitle: 'Octant Octave Resolution (φ = 3/8 = 0.375)',
    description: 'The target emitter produces an eigenphase of 3/8. A 2-bit register cannot resolve eighths. Switch to 3-bit precision, locate the signal in range 0.35–0.40, and estimate within ±0.025.',
    difficulty: 'Intermediate',
    educationalConcept: 'Each added estimation qubit doubles resolution: 3 qubits divide the phase circle into 8 bins of width 1/8 = 0.125.',
    hints: [
      'Select 3 Bits precision: 2 bits cannot resolve fractions of 8.',
      'Target S2 (Theta): run QPE and observe the peak at |011⟩.',
      'Binary fraction calculation: 0/2 + 1/4 + 1/8 = 0.250 + 0.125 = 0.375.',
      'Set your estimate to 0.375 and lock the signal.',
    ],
    initialState: { selectedSignalId: null, playerPhaseEstimate: null, hasRunQPE: false },
    targetState: { targetSignalId: 'S2', truePhase: 0.375 },
    tolerance: 0.025,
    targetSignalId: 'S2',
    targetPhaseRange: [0.35, 0.40],
    targetTolerance: 0.025,
    allowedPrecisionBits: [2, 3, 4],
    requiredPrecisionBits: 3,
    signals: [
      {
        id: 'S1',
        name: 'Iota Probe',
        truePhase: 0.125,
        knownRegion: '0.10–0.15',
        frequencyBand: 'C-Band',
        description: 'Eighth-turn calibration pulse (1/8 = 0.125).',
      },
      {
        id: 'S2',
        name: 'Theta Transponder',
        truePhase: 0.375,
        knownRegion: '0.35–0.40',
        frequencyBand: 'X-Band',
        description: 'Mission target with phase 3/8 = 0.375.',
      },
      {
        id: 'S3',
        name: 'Kappa Beacon',
        truePhase: 0.625,
        knownRegion: '0.60–0.65',
        frequencyBand: 'Ku-Band',
        description: 'Five-eighths decoy beacon (5/8 = 0.625).',
      },
    ],
    xpReward: 400,
    starThresholds: { threeStars: 350, fourStars: 400, fiveStars: 450 },
    phaseLevel: {
      truePhase: 0.375,
      estimationQubits: 3,
      tolerance: 0.025,
      difficulty: 'Intermediate',
      description: 'Three-eighths turn φ = 0.375',
    },
  },

  // LEVEL 5: CHOOSE YOUR PRECISION
  {
    id: 't5_l5',
    trackId: 'phase-estimation',
    trackNumber: 5,
    levelNumber: 5,
    title: 'Choose Your Precision',
    subtitle: 'Resolving Adjacent Sixteenths (φ = 7/16 = 0.4375)',
    description: 'Two candidate signals lie very close together (0.375 and 0.4375). A 3-bit QPE register cannot separate them cleanly. Upgrade to 4-bit precision, identify the 0.4375 signal, and lock within ±0.02.',
    difficulty: 'Advanced',
    educationalConcept: 'When two signals or an unknown phase fall between 3-bit bins, 4 estimation qubits provide 16 bins of width 1/16 = 0.0625, resolving the true frequency.',
    hints: [
      'If you use 3 bits, 0.4375 splits probability across |011⟩ (0.375) and |100⟩ (0.500). Switch to 4 Bits.',
      'Target S2 (Lambda) and execute a 4-bit QPE experiment.',
      'With 4 bits, the histogram displays an exact peak at |0111⟩: 7/16 = 0.4375.',
      'Lock with estimated phase 0.438.',
    ],
    initialState: { selectedSignalId: null, playerPhaseEstimate: null, hasRunQPE: false },
    targetState: { targetSignalId: 'S2', truePhase: 0.4375 },
    tolerance: 0.02,
    targetSignalId: 'S2',
    targetPhaseRange: [0.42, 0.46],
    targetTolerance: 0.02,
    allowedPrecisionBits: [2, 3, 4],
    requiredPrecisionBits: 4,
    signals: [
      {
        id: 'S1',
        name: 'Mu Signal',
        truePhase: 0.375,
        knownRegion: '0.36–0.39',
        frequencyBand: 'X-Band',
        description: 'Adjacent 3/8 signal source.',
      },
      {
        id: 'S2',
        name: 'Lambda Anomaly',
        truePhase: 0.4375,
        knownRegion: '0.42–0.46',
        frequencyBand: 'X-Band',
        description: 'Target signal at 7/16 = 0.4375.',
      },
      {
        id: 'S3',
        name: 'Nu Transmitter',
        truePhase: 0.625,
        knownRegion: '0.60–0.65',
        frequencyBand: 'Ku-Band',
        description: 'Decoy beacon at 5/8 = 0.625.',
      },
    ],
    xpReward: 450,
    starThresholds: { threeStars: 400, fourStars: 450, fiveStars: 500 },
    phaseLevel: {
      truePhase: 0.4375,
      estimationQubits: 4,
      tolerance: 0.02,
      difficulty: 'Advanced',
      description: 'Precision target φ = 0.4375',
    },
  },

  // LEVEL 6: UNKNOWN SIGNAL
  {
    id: 't5_l6',
    trackId: 'phase-estimation',
    trackNumber: 5,
    levelNumber: 6,
    title: 'Unknown Signal',
    subtitle: 'Blind Quantum Radar Search (Target: 0.58–0.65)',
    description: 'Three deep-space radar targets have completely UNKNOWN phases. Scan the signals with QPE, identify the one whose phase lies in the 0.58–0.65 window, and estimate its phase within ±0.02.',
    difficulty: 'Advanced',
    educationalConcept: 'In real-world quantum sensing, true eigenphases are completely unknown. The operator must run QPE and deduce the phase purely from measured basis states.',
    hints: [
      'All three signals show "UNKNOWN" on the spectrum. You must run QPE on each candidate to discover their phases.',
      'S1 peaks at |001⟩ (0.125), S2 peaks at |101⟩ (0.625), S3 peaks at |111⟩ (0.875).',
      'Signal S2 (Xi) falls directly into the target range 0.58–0.65: 5/8 = 0.625.',
      'Target S2 with estimated phase 0.625.',
    ],
    initialState: { selectedSignalId: null, playerPhaseEstimate: null, hasRunQPE: false },
    targetState: { targetSignalId: 'S2', truePhase: 0.625 },
    tolerance: 0.02,
    targetSignalId: 'S2',
    targetPhaseRange: [0.58, 0.65],
    targetTolerance: 0.02,
    allowedPrecisionBits: [3, 4],
    requiredPrecisionBits: 3,
    signals: [
      {
        id: 'S1',
        name: 'Omicron Echo',
        truePhase: 0.125,
        knownRegion: 'UNKNOWN',
        frequencyBand: 'Deep Space',
      },
      {
        id: 'S2',
        name: 'Xi Pulsar',
        truePhase: 0.625,
        knownRegion: 'UNKNOWN',
        frequencyBand: 'Deep Space',
        description: 'Mission target with phase 5/8 = 0.625.',
      },
      {
        id: 'S3',
        name: 'Pi Carrier',
        truePhase: 0.875,
        knownRegion: 'UNKNOWN',
        frequencyBand: 'Deep Space',
      },
    ],
    xpReward: 500,
    starThresholds: { threeStars: 450, fourStars: 500, fiveStars: 550 },
    phaseLevel: {
      truePhase: 0.625,
      estimationQubits: 3,
      tolerance: 0.02,
      difficulty: 'Advanced',
      description: 'Unknown signal φ = 0.625',
    },
  },

  // LEVEL 7: MEASUREMENT NOISE / SAMPLING
  {
    id: 't5_l7',
    trackId: 'phase-estimation',
    trackNumber: 5,
    levelNumber: 7,
    title: 'Measurement Noise & Sampling',
    subtitle: 'Probabilistic Fluctuation (φ = 5/16 = 0.3125)',
    description: 'Quantum measurements are fundamentally probabilistic. The target emitter has phase 5/16 (0.3125). Run multiple shots (50 or 100) to observe statistical fluctuations around the theoretical distribution and estimate within ±0.02.',
    difficulty: 'Advanced',
    educationalConcept: 'Single measurement shots yield probabilistic outcomes. Repeated shots build empirical histograms that converge toward the underlying quantum probability distribution.',
    hints: [
      'Select 4 bits precision to resolve sixteenths.',
      'Click "Run 100 Shots" to sample a full empirical distribution.',
      'Notice that the observed counts fluctuate around the theoretical bars, with the highest count concentrated at |0101⟩ (5/16 = 0.3125).',
      'Lock onto S1 with phase 0.313.',
    ],
    initialState: { selectedSignalId: null, playerPhaseEstimate: null, hasRunQPE: false },
    targetState: { targetSignalId: 'S1', truePhase: 0.3125 },
    tolerance: 0.02,
    targetSignalId: 'S1',
    targetPhaseRange: [0.29, 0.34],
    targetTolerance: 0.02,
    allowedPrecisionBits: [3, 4],
    requiredPrecisionBits: 4,
    signals: [
      {
        id: 'S1',
        name: 'Rho Resonator',
        truePhase: 0.3125,
        knownRegion: '0.28–0.35',
        frequencyBand: 'Quantum Waveguide',
        description: 'Continuous target source at 5/16 = 0.3125.',
      },
      {
        id: 'S2',
        name: 'Sigma Noise Source',
        truePhase: 0.6875,
        knownRegion: '0.65–0.72',
        frequencyBand: 'Decoy Noise',
      },
    ],
    xpReward: 550,
    starThresholds: { threeStars: 500, fourStars: 550, fiveStars: 600 },
    phaseLevel: {
      truePhase: 0.3125,
      estimationQubits: 4,
      tolerance: 0.02,
      difficulty: 'Advanced',
      description: 'Sampling fluctuation φ = 0.3125',
    },
  },

  // LEVEL 8: MULTIPLE SIGNALS
  {
    id: 't5_l8',
    trackId: 'phase-estimation',
    trackNumber: 5,
    levelNumber: 8,
    title: 'Multi-Signal Spectrum Sweep',
    subtitle: 'Dense Radar Array (Target: 0.65–0.72)',
    description: 'Four active quantum signals crowd the radar array. Scan the contacts, isolate the signal emitting in the 0.65–0.72 phase window, and estimate within ±0.02.',
    difficulty: 'Expert',
    educationalConcept: 'In a multi-emitter quantum environment, the operator systematically samples each signal, discriminates spurious signals, and homes in on the mission target.',
    hints: [
      'Four contacts are active: S1, S2, S3, S4.',
      'S3 (Upsilon) is the candidate in the 0.65–0.72 spectrum.',
      'Using 4 bits on S3 reveals a peak at |1011⟩: 11/16 = 0.6875.',
      'Lock S3 with estimated phase 0.688.',
    ],
    initialState: { selectedSignalId: null, playerPhaseEstimate: null, hasRunQPE: false },
    targetState: { targetSignalId: 'S3', truePhase: 0.6875 },
    tolerance: 0.02,
    targetSignalId: 'S3',
    targetPhaseRange: [0.65, 0.72],
    targetTolerance: 0.02,
    allowedPrecisionBits: [3, 4],
    requiredPrecisionBits: 4,
    signals: [
      {
        id: 'S1',
        name: 'Tau Emitter',
        truePhase: 0.1875,
        knownRegion: 'UNKNOWN',
        frequencyBand: 'Channel 1',
      },
      {
        id: 'S2',
        name: 'Phi Repeater',
        truePhase: 0.375,
        knownRegion: 'UNKNOWN',
        frequencyBand: 'Channel 2',
      },
      {
        id: 'S3',
        name: 'Upsilon Core',
        truePhase: 0.6875,
        knownRegion: 'UNKNOWN',
        frequencyBand: 'Target Band',
        description: 'Target signal at 11/16 = 0.6875.',
      },
      {
        id: 'S4',
        name: 'Chi Jammer',
        truePhase: 0.8125,
        knownRegion: 'UNKNOWN',
        frequencyBand: 'Channel 4',
      },
    ],
    xpReward: 600,
    starThresholds: { threeStars: 550, fourStars: 600, fiveStars: 650 },
    phaseLevel: {
      truePhase: 0.6875,
      estimationQubits: 4,
      tolerance: 0.02,
      difficulty: 'Expert',
      description: 'Multi-signal sweep φ = 0.6875',
    },
  },

  // LEVEL 9: RESOURCE CHALLENGE
  {
    id: 't5_l9',
    trackId: 'phase-estimation',
    trackNumber: 5,
    levelNumber: 9,
    title: 'Resource Budget Challenge',
    subtitle: 'Limited Scans (5 Scans Max, Target ≈ 0.375)',
    description: 'Radar energy reserves are constrained: you have a strict budget of 5 QPE scans. Locate the signal closest to 0.375, avoid wasting scans on decoys, and estimate within ±0.02.',
    difficulty: 'Expert',
    educationalConcept: 'Quantum measurement consumes experimental resources. Efficient operators plan scan precision and shot budgets to extract maximum information per scan.',
    hints: [
      'You only have 5 scans! Check preliminary region tags before initiating QPE.',
      'S2 (Psi) is tagged near 0.35–0.40. Target S2 directly.',
      'Run a 3-bit or 4-bit QPE scan on S2 to observe the peak at 0.375 (3/8).',
      'Lock S2 with phase 0.375 to complete the mission within budget.',
    ],
    initialState: { selectedSignalId: null, playerPhaseEstimate: null, hasRunQPE: false, scansUsed: 0 },
    targetState: { targetSignalId: 'S2', truePhase: 0.375 },
    tolerance: 0.02,
    targetSignalId: 'S2',
    targetPhaseRange: [0.35, 0.40],
    targetTolerance: 0.02,
    allowedPrecisionBits: [3, 4],
    requiredPrecisionBits: 3,
    allowedScans: 5,
    timeLimit: 75,
    signals: [
      {
        id: 'S1',
        name: 'Alpha Decoy',
        truePhase: 0.125,
        knownRegion: '0.10–0.15',
        frequencyBand: 'Ch 1',
      },
      {
        id: 'S2',
        name: 'Psi Target',
        truePhase: 0.375,
        knownRegion: '0.35–0.40',
        frequencyBand: 'Ch 2',
        description: 'Mission target with phase 0.375.',
      },
      {
        id: 'S3',
        name: 'Beta Decoy',
        truePhase: 0.5625,
        knownRegion: '0.54–0.58',
        frequencyBand: 'Ch 3',
      },
      {
        id: 'S4',
        name: 'Gamma Decoy',
        truePhase: 0.875,
        knownRegion: '0.85–0.90',
        frequencyBand: 'Ch 4',
      },
    ],
    xpReward: 700,
    starThresholds: { threeStars: 650, fourStars: 700, fiveStars: 750 },
    phaseLevel: {
      truePhase: 0.375,
      estimationQubits: 3,
      tolerance: 0.02,
      difficulty: 'Expert',
      description: 'Resource limited φ = 0.375',
    },
  },

  // LEVEL 10: QUANTUM RADAR MASTER
  {
    id: 't5_l10',
    trackId: 'phase-estimation',
    trackNumber: 5,
    levelNumber: 10,
    title: 'Quantum Radar Master',
    subtitle: 'The Grand Final Track 5 Challenge',
    description: 'Four deep-space quantum signals with completely hidden phases are cloaked in quantum noise. Mission: Identify the signal closest to 0.625 and estimate its phase within ±0.015 using optimum precision under a 6-scan budget.',
    difficulty: 'Expert',
    educationalConcept: 'Mastery of Quantum Phase Estimation requires coordinating signal identification, precision tradeoffs, inverse-QFT interpretation, and high-accuracy phase locking.',
    hints: [
      'Four unknown signals are in play with a 6-scan limit. Select a candidate and use 3 or 4 bits.',
      'S3 (Omega) has true phase 0.625 (5/8), which is the exact match for the mission criteria.',
      'A 3-bit QPE run on S3 yields peak bitstring |101⟩: 5/8 = 0.625.',
      'Lock onto S3 with estimated phase 0.625 to become the Quantum Radar Master!',
    ],
    initialState: { selectedSignalId: null, playerPhaseEstimate: null, hasRunQPE: false, scansUsed: 0 },
    targetState: { targetSignalId: 'S3', truePhase: 0.625 },
    tolerance: 0.015,
    targetSignalId: 'S3',
    targetPhaseRange: [0.61, 0.64],
    targetTolerance: 0.015,
    allowedPrecisionBits: [2, 3, 4],
    requiredPrecisionBits: 3,
    allowedScans: 6,
    timeLimit: 90,
    signals: [
      {
        id: 'S1',
        name: 'Beacon Echo 1',
        truePhase: 0.25,
        knownRegion: 'UNKNOWN',
        frequencyBand: 'Deep Band 1',
      },
      {
        id: 'S2',
        name: 'Beacon Echo 2',
        truePhase: 0.4375,
        knownRegion: 'UNKNOWN',
        frequencyBand: 'Deep Band 2',
      },
      {
        id: 'S3',
        name: 'Omega Singularity',
        truePhase: 0.625,
        knownRegion: 'UNKNOWN',
        frequencyBand: 'Classified',
        description: 'Grand final target with phase 5/8 = 0.625.',
      },
      {
        id: 'S4',
        name: 'Beacon Echo 4',
        truePhase: 0.8125,
        knownRegion: 'UNKNOWN',
        frequencyBand: 'Deep Band 4',
      },
    ],
    xpReward: 1000,
    starThresholds: { threeStars: 900, fourStars: 1000, fiveStars: 1200 },
    phaseLevel: {
      truePhase: 0.625,
      estimationQubits: 4,
      tolerance: 0.015,
      difficulty: 'Expert',
      description: 'Quantum Radar Master φ = 0.625',
    },
  },
];
