// Track 5 — Quantum Phase Estimation Level Definitions

import type { LevelDefinition } from '../types';
import type { PhaseLevelDefinition } from '../engines/phaseEstimationEngine';

export interface PhaseLevelConfig extends LevelDefinition {
  phaseLevel: PhaseLevelDefinition;
}

export const TRACK_5_LEVELS: PhaseLevelConfig[] = [
  {
    id: 't5_l1',
    trackId: 'phase-estimation',
    trackNumber: 5,
    levelNumber: 1,
    title: 'The Half-Circle Eigenphase',
    subtitle: 'φ = 1/2 (Binary 0.100)',
    description: 'An unknown unitary operator imparts eigenphase e^(2πi · 0.5) = -1. Scan the signal and locate φ = 0.500.',
    difficulty: 'Beginner',
    educationalConcept: 'Quantum Phase Estimation estimates the unknown phase φ in U|ψ⟩ = e^(2πiφ)|ψ⟩. An eigenphase of 0.5 corresponds to a 180° rotation.',
    hints: [
      'Look at the QPE measurement readout: the peak probability is centered on bitstring |100⟩.',
      'In 3-bit binary fraction, 100_2 = 1·(1/2) + 0·(1/4) + 0·(1/8) = 0.500.',
      'Set the estimation scanner dial to 0.500.',
    ],
    initialState: { scannerPhase: 0.1 },
    targetState: { truePhase: 0.5 },
    tolerance: 0.05,
    phaseLevel: {
      truePhase: 0.5,
      estimationQubits: 3,
      tolerance: 0.05,
      difficulty: 'Beginner',
      description: 'Phase φ = 0.500',
    },
  },
  {
    id: 't5_l2',
    trackId: 'phase-estimation',
    trackNumber: 5,
    levelNumber: 2,
    title: 'Quarter-Turn Calibration',
    subtitle: 'φ = 1/4 (Binary 0.010)',
    description: 'The quantum signal carries an eigenphase of 90° (0.250). Tune your phase scanner into the resonance peak.',
    difficulty: 'Beginner',
    educationalConcept: 'Controlled-U operations accumulate phase on the control register in powers of 2. An eigenphase of 1/4 (0.250) activates bit 2.',
    hints: [
      'The readout peak is at |010⟩.',
      'In binary fraction: 010_2 = 0/2 + 1/4 + 0/8 = 0.250.',
      'Dial your scanner to 0.250.',
    ],
    initialState: { scannerPhase: 0.8 },
    targetState: { truePhase: 0.25 },
    tolerance: 0.05,
    phaseLevel: {
      truePhase: 0.25,
      estimationQubits: 3,
      tolerance: 0.05,
      difficulty: 'Beginner',
      description: 'Phase φ = 0.250',
    },
  },
  {
    id: 't5_l3',
    trackId: 'phase-estimation',
    trackNumber: 5,
    levelNumber: 3,
    title: 'Eighth-Turn Precision',
    subtitle: 'φ = 1/8 (Binary 0.001)',
    description: 'The operator executes a T-gate style rotation. Read the 3-qubit estimation register and submit the phase.',
    difficulty: 'Intermediate',
    educationalConcept: 'With 3 estimation qubits, the minimum resolvable binary fraction step size is 1/2^3 = 1/8 = 0.125.',
    hints: [
      'Observe the peak at bitstring |001⟩.',
      'Binary value: 1/8 = 0.125.',
      'Position the dial at 0.125.',
    ],
    initialState: { scannerPhase: 0.6 },
    targetState: { truePhase: 0.125 },
    tolerance: 0.04,
    phaseLevel: {
      truePhase: 0.125,
      estimationQubits: 3,
      tolerance: 0.04,
      difficulty: 'Intermediate',
      description: 'Phase φ = 0.125',
    },
  },
  {
    id: 't5_l4',
    trackId: 'phase-estimation',
    trackNumber: 5,
    levelNumber: 4,
    title: 'Composite Binary Readout',
    subtitle: 'φ = 3/8 (Binary 0.011)',
    description: 'Both bit 2 and bit 3 are active in the QPE histogram (|011⟩). Calculate and estimate the composite decimal phase.',
    difficulty: 'Intermediate',
    educationalConcept: 'Inverse Quantum Fourier Transform maps accumulated phases directly into computational basis bitstrings representing the binary expansion of φ.',
    hints: [
      'The histogram peaks at |011⟩.',
      'Compute: 0/2 + 1/4 + 1/8 = 0.250 + 0.125 = 0.375.',
      'Submit estimated phase 0.375.',
    ],
    initialState: { scannerPhase: 0.1 },
    targetState: { truePhase: 0.375 },
    tolerance: 0.035,
    phaseLevel: {
      truePhase: 0.375,
      estimationQubits: 3,
      tolerance: 0.035,
      difficulty: 'Intermediate',
      description: 'Phase φ = 0.375',
    },
  },
  {
    id: 't5_l5',
    trackId: 'phase-estimation',
    trackNumber: 5,
    levelNumber: 5,
    title: 'High-Band Signal',
    subtitle: 'φ = 5/8 (Binary 0.101)',
    description: 'The signal frequency registers at bitstring |101⟩. Match your estimation scanner to the incoming eigenphase.',
    difficulty: 'Advanced',
    educationalConcept: 'Eigenphases exceeding 0.5 occupy the second half of the unit circle. 101_2 corresponds to 1/2 + 1/8 = 5/8 = 0.625.',
    hints: [
      'Peak bitstring is |101⟩.',
      'Calculation: 4/8 + 1/8 = 5/8 = 0.625.',
      'Adjust the scanner dial to 0.625.',
    ],
    initialState: { scannerPhase: 0.2 },
    targetState: { truePhase: 0.625 },
    tolerance: 0.03,
    phaseLevel: {
      truePhase: 0.625,
      estimationQubits: 3,
      tolerance: 0.03,
      difficulty: 'Advanced',
      description: 'Phase φ = 0.625',
    },
  },
  {
    id: 't5_l6',
    trackId: 'phase-estimation',
    trackNumber: 6,
    levelNumber: 6,
    title: 'Master Quantum Signal Scanner',
    subtitle: 'Non-Exact Phase Interpolation',
    description: 'The signal phase φ = 0.312 lies between exact 3-qubit grid points (2/8=0.250 and 3/8=0.375). Inspect the shared probability distribution and estimate.',
    difficulty: 'Expert',
    educationalConcept: 'When φ is not an exact dyadic fraction k/2^n, QPE creates a sinc-like probability distribution peaking at the closest binary fractions.',
    hints: [
      'Notice that probability mass is split between |010⟩ (0.250) and |011⟩ (0.375).',
      'The true phase lies between these two peaks, closer to |010⟩.',
      'Try an estimate around 0.310 - 0.315.',
    ],
    initialState: { scannerPhase: 0.7 },
    targetState: { truePhase: 0.312 },
    tolerance: 0.03,
    phaseLevel: {
      truePhase: 0.312,
      estimationQubits: 3,
      tolerance: 0.03,
      difficulty: 'Expert',
      description: 'Continuous non-dyadic phase φ = 0.312',
    },
  },
];
