// Track 4 — Quantum Tunneling (Tunnel Run) Level Definitions
// 10 Progressive Levels covering single-barrier discovery to 4-barrier multi-potential master challenge.

import type { LevelDefinition } from '../types';
import type { TunnelingLevelConfig } from '../engines/tunnelingEngine';

export interface TunnelLevelConfig extends LevelDefinition {
  tunnelingLevel: TunnelingLevelConfig;
}

export const TRACK_4_LEVELS: TunnelLevelConfig[] = [
  // LEVEL 1 — DISCOVER TUNNELING (Group 1: 1 Barrier, Adjust Energy)
  {
    id: 't4_l1',
    trackId: 'quantum-tunneling',
    trackNumber: 4,
    levelNumber: 1,
    title: 'Discover Tunneling',
    subtitle: 'Penetrating the Classically Forbidden Region',
    description: 'In classical physics, a particle with energy E < V0 is strictly blocked by a potential barrier. In quantum mechanics, the wave function penetrates the barrier, producing a non-zero transmission probability. Adjust the particle energy to reach the target transmission.',
    difficulty: 'Beginner',
    educationalConcept: 'When E < V0, the Schrödinger equation yields an evanescent wave inside the barrier. Because the barrier is finite, a non-zero probability amplitude emerges on the far side.',
    hints: [
      'In this model, particle energy E must remain below the barrier height V0 = 1.00.',
      'Higher particle energy (closer to the barrier crest) increases the transmission probability.',
      'Slide the Particle Energy toward 0.81 to match the 70% target range.',
    ],
    initialState: {
      particleEnergy: 0.30,
      barriers: [{ id: 'b1', height: 1.0, width: 0.8, adjustableHeight: false, adjustableWidth: false }],
    },
    targetState: { targetTransmission: 0.70, tolerance: 0.03 },
    tolerance: 0.03,
    tunnelingLevel: {
      id: 't4_l1',
      trackId: 'quantum-tunneling',
      trackNumber: 4,
      levelNumber: 1,
      title: 'Discover Tunneling',
      subtitle: 'Penetrating the Classically Forbidden Region',
      description: 'Adjust particle energy to reach 70% ± 3% transmission.',
      difficulty: 'Beginner',
      educationalConcept: 'Quantum tunneling permits transmission even when particle energy is below the potential barrier height (E < V0).',
      hints: [
        'Notice that transmission is non-zero even though E < V0.',
        'Increasing particle energy reduces the barrier deficit (V0 - E), raising transmission.',
        'Adjust Particle Energy toward 0.81.',
      ],
      initialState: {
        particleEnergy: 0.30,
        barriers: [{ id: 'b1', height: 1.0, width: 0.8, adjustableHeight: false, adjustableWidth: false }],
      },
      targetTransmission: 0.70,
      targetTolerance: 0.03,
      energyRange: { min: 0.15, max: 0.95 },
      adjustableEnergy: true,
    },
  },

  // LEVEL 2 — BARRIER WIDTH (Group 2: 1 Barrier, Adjust Width)
  {
    id: 't4_l2',
    trackId: 'quantum-tunneling',
    trackNumber: 4,
    levelNumber: 2,
    title: 'Barrier Width',
    subtitle: 'Exponential Decay with Thickness',
    description: 'The probability wave decays exponentially inside the barrier (ψ ∝ e^(-κx)). Keep the particle energy fixed and adjust the barrier width to reach the target transmission.',
    difficulty: 'Beginner',
    educationalConcept: 'Transmission decays exponentially with barrier thickness (a). Even a modest reduction in width sharply increases the likelihood of tunneling.',
    hints: [
      'Particle energy is fixed at E = 0.60, and barrier height is V0 = 1.00.',
      'A thicker barrier suppresses tunneling. You need more transmission, so narrow the barrier.',
      'Adjust the Barrier Width toward 1.25 to hit the 35% target.',
    ],
    initialState: {
      particleEnergy: 0.60,
      barriers: [{ id: 'b1', height: 1.0, width: 1.80, minWidth: 0.3, maxWidth: 2.0, adjustableHeight: false, adjustableWidth: true }],
    },
    targetState: { targetTransmission: 0.35, tolerance: 0.02 },
    tolerance: 0.02,
    tunnelingLevel: {
      id: 't4_l2',
      trackId: 'quantum-tunneling',
      trackNumber: 4,
      levelNumber: 2,
      title: 'Barrier Width',
      subtitle: 'Exponential Decay with Thickness',
      description: 'Tune barrier width to achieve 35% ± 2% transmission.',
      difficulty: 'Beginner',
      educationalConcept: 'Tunneling probability decreases exponentially as barrier width increases.',
      hints: [
        'A wide barrier attenuates the wave packet heavily.',
        'Decreasing width allows a larger fraction of the wave function to penetrate through.',
        'Target width is around 1.25.',
      ],
      initialState: {
        particleEnergy: 0.60,
        barriers: [{ id: 'b1', height: 1.0, width: 1.80, minWidth: 0.3, maxWidth: 2.0, adjustableHeight: false, adjustableWidth: true }],
      },
      targetTransmission: 0.35,
      targetTolerance: 0.02,
      energyRange: { min: 0.60, max: 0.60 },
      adjustableEnergy: false,
    },
  },

  // LEVEL 3 — BARRIER HEIGHT (Group 3: 1 Barrier, Adjust Height)
  {
    id: 't4_l3',
    trackId: 'quantum-tunneling',
    trackNumber: 4,
    levelNumber: 3,
    title: 'Barrier Height',
    subtitle: 'Decay Constant & Potential Energy',
    description: 'The wave decay constant is κ = √(2m(V0 - E))/ħ. Increasing barrier height steepens the exponential decay rate. Calibrate the barrier height to meet the target transmission.',
    difficulty: 'Beginner',
    educationalConcept: 'A taller potential barrier increases the potential energy difference (V0 - E), resulting in a larger decay parameter κ and lower transmission probability.',
    hints: [
      'Particle energy is fixed at E = 0.50 and width is fixed at a = 0.70.',
      'Currently the barrier is very tall (V0 = 2.40), causing severe attenuation.',
      'Lower the barrier height toward 1.35 to reach the 45% target range.',
    ],
    initialState: {
      particleEnergy: 0.50,
      barriers: [{ id: 'b1', height: 2.40, width: 0.70, minHeight: 0.65, maxHeight: 2.60, adjustableHeight: true, adjustableWidth: false }],
    },
    targetState: { targetTransmission: 0.45, tolerance: 0.03 },
    tolerance: 0.03,
    tunnelingLevel: {
      id: 't4_l3',
      trackId: 'quantum-tunneling',
      trackNumber: 4,
      levelNumber: 3,
      title: 'Barrier Height',
      subtitle: 'Decay Constant & Potential Energy',
      description: 'Tune barrier height to reach 45% ± 3% transmission.',
      difficulty: 'Beginner',
      educationalConcept: 'Increasing barrier height V0 increases κ, accelerating the rate of spatial decay.',
      hints: [
        'Higher barriers diminish tunneling for fixed particle energy.',
        'Lowering the barrier crest closer to E = 0.50 boosts transmission.',
        'Set Barrier Height to approximately 1.35.',
      ],
      initialState: {
        particleEnergy: 0.50,
        barriers: [{ id: 'b1', height: 2.40, width: 0.70, minHeight: 0.65, maxHeight: 2.60, adjustableHeight: true, adjustableWidth: false }],
      },
      targetTransmission: 0.45,
      targetTolerance: 0.03,
      energyRange: { min: 0.50, max: 0.50 },
      adjustableEnergy: false,
    },
  },

  // LEVEL 4 — TWO VARIABLES (Group 4: Energy + Width)
  {
    id: 't4_l4',
    trackId: 'quantum-tunneling',
    trackNumber: 4,
    levelNumber: 4,
    title: 'Energy & Width Coordination',
    subtitle: 'Balancing Incident Energy with Thickness',
    description: 'Simultaneously adjust particle energy and barrier width. Compensate for thickness changes by modulating particle kinetic energy.',
    difficulty: 'Intermediate',
    educationalConcept: 'A thicker barrier can be compensated by raising particle energy closer to V0, illustrating the two complementary physical knobs controlling quantum transmission.',
    hints: [
      'Both Particle Energy and Barrier Width are adjustable.',
      'Try setting Particle Energy to around 0.65 and Barrier Width to around 0.85.',
      'Check that your probability enters 60% ± 2%.',
    ],
    initialState: {
      particleEnergy: 0.35,
      barriers: [{ id: 'b1', height: 1.00, width: 1.40, minWidth: 0.3, maxWidth: 1.8, adjustableHeight: false, adjustableWidth: true }],
    },
    targetState: { targetTransmission: 0.60, tolerance: 0.02 },
    tolerance: 0.02,
    tunnelingLevel: {
      id: 't4_l4',
      trackId: 'quantum-tunneling',
      trackNumber: 4,
      levelNumber: 4,
      title: 'Energy & Width Coordination',
      subtitle: 'Balancing Incident Energy with Thickness',
      description: 'Coordinate particle energy and barrier width to reach 60% ± 2%.',
      difficulty: 'Intermediate',
      educationalConcept: 'Particle energy and barrier width interact nonlinearly to define the tunneling transmission factor.',
      hints: [
        'Initial transmission (14%) is far below the 60% target.',
        'Increase particle energy toward 0.65 while narrowing the barrier to ~0.85.',
        'Fine-tune width to land inside the 58%–62% window.',
      ],
      initialState: {
        particleEnergy: 0.35,
        barriers: [{ id: 'b1', height: 1.00, width: 1.40, minWidth: 0.3, maxWidth: 1.8, adjustableHeight: false, adjustableWidth: true }],
      },
      targetTransmission: 0.60,
      targetTolerance: 0.02,
      energyRange: { min: 0.20, max: 0.95 },
      adjustableEnergy: true,
    },
  },

  // LEVEL 5 — HEIGHT + WIDTH (Group 5: Barrier Dimensions)
  {
    id: 't4_l5',
    trackId: 'quantum-tunneling',
    trackNumber: 4,
    levelNumber: 5,
    title: 'Barrier Geometry',
    subtitle: 'Sculpting the Potential Profile',
    description: 'With particle energy fixed at E = 0.65, shape the barrier profile by adjusting both its height and width to reach the target transmission of 50%.',
    difficulty: 'Intermediate',
    educationalConcept: 'The barrier integral ∫√(V(x) - E) dx dictates tunneling probability. A tall narrow barrier and a low wide barrier can yield identical transmission probabilities.',
    hints: [
      'Particle energy is locked at E = 0.65.',
      'Adjust both Barrier Height and Barrier Width.',
      'Try Barrier Height ≈ 1.15 and Barrier Width ≈ 0.90 to hit 50%.',
    ],
    initialState: {
      particleEnergy: 0.65,
      barriers: [{ id: 'b1', height: 2.00, width: 1.40, minHeight: 0.8, maxHeight: 2.4, minWidth: 0.3, maxWidth: 1.8, adjustableHeight: true, adjustableWidth: true }],
    },
    targetState: { targetTransmission: 0.50, tolerance: 0.02 },
    tolerance: 0.02,
    tunnelingLevel: {
      id: 't4_l5',
      trackId: 'quantum-tunneling',
      trackNumber: 4,
      levelNumber: 5,
      title: 'Barrier Geometry',
      subtitle: 'Sculpting the Potential Profile',
      description: 'Tune barrier height and width to achieve 50% ± 2% transmission.',
      difficulty: 'Intermediate',
      educationalConcept: 'Multiple barrier geometries can produce the exact same quantum transmission probability.',
      hints: [
        'Initial barrier is both too high and too wide (3.5% transmission).',
        'Reduce barrier height towards 1.15 and barrier width towards 0.90.',
        'Target window is 48% to 52%.',
      ],
      initialState: {
        particleEnergy: 0.65,
        barriers: [{ id: 'b1', height: 2.00, width: 1.40, minHeight: 0.8, maxHeight: 2.4, minWidth: 0.3, maxWidth: 1.8, adjustableHeight: true, adjustableWidth: true }],
      },
      targetTransmission: 0.50,
      targetTolerance: 0.02,
      energyRange: { min: 0.65, max: 0.65 },
      adjustableEnergy: false,
    },
  },

  // LEVEL 6 — THREE PARAMETERS (Group 6: Energy + Height + Width, Limited Moves)
  {
    id: 't4_l6',
    trackId: 'quantum-tunneling',
    trackNumber: 4,
    levelNumber: 6,
    title: 'Optimization Chamber',
    subtitle: 'Triple-Parameter Optimization',
    description: 'All three primary parameters are active: Particle Energy, Barrier Height, and Barrier Width. Reach 68% ± 2% transmission within 8 adjustments.',
    difficulty: 'Intermediate',
    educationalConcept: 'Global parameter optimization under constraints: finding an efficient trajectory through multidimensional quantum configuration space.',
    hints: [
      'You have full control over Energy, Height, and Width.',
      'Keep Particle Energy strictly below Barrier Height (E < V0).',
      'Aim for E ≈ 0.60, V0 ≈ 1.00, and a ≈ 0.70 to reach 68%.',
    ],
    initialState: {
      particleEnergy: 0.40,
      barriers: [{ id: 'b1', height: 1.50, width: 1.20, minHeight: 0.9, maxHeight: 2.0, minWidth: 0.3, maxWidth: 1.6, adjustableHeight: true, adjustableWidth: true }],
    },
    targetState: { targetTransmission: 0.68, tolerance: 0.02 },
    tolerance: 0.02,
    constraints: { maxMoves: 8 },
    tunnelingLevel: {
      id: 't4_l6',
      trackId: 'quantum-tunneling',
      trackNumber: 4,
      levelNumber: 6,
      title: 'Optimization Chamber',
      subtitle: 'Triple-Parameter Optimization',
      description: 'Reach 68% ± 2% within 8 parameter adjustments.',
      difficulty: 'Intermediate',
      educationalConcept: 'Multivariate quantum parameter optimization under discrete move constraints.',
      hints: [
        'Plan adjustments deliberately to conserve your move allowance.',
        'Raise particle energy closer to barrier height while slimming width.',
        'Target configuration: E ≈ 0.60, V0 ≈ 1.00, a ≈ 0.70.',
      ],
      initialState: {
        particleEnergy: 0.40,
        barriers: [{ id: 'b1', height: 1.50, width: 1.20, minHeight: 0.9, maxHeight: 2.0, minWidth: 0.3, maxWidth: 1.6, adjustableHeight: true, adjustableWidth: true }],
      },
      targetTransmission: 0.68,
      targetTolerance: 0.02,
      energyRange: { min: 0.25, max: 1.20 },
      adjustableEnergy: true,
      allowedMoves: 8,
    },
  },

  // LEVEL 7 — MULTIPLE BARRIERS: DOUBLE BARRIER RESONANCE (Group 7)
  {
    id: 't4_l7',
    trackId: 'quantum-tunneling',
    trackNumber: 4,
    levelNumber: 7,
    title: 'Double Barrier Resonance',
    subtitle: 'Quantum Well Phase Interference',
    description: 'Two identical barriers separated by a potential well create an internal quantum cavity. Waves reflecting between the barriers constructively interfere at specific resonant energies, creating transmission peaks. Tune particle energy to match the target resonance.',
    difficulty: 'Advanced',
    educationalConcept: 'In a double barrier structure, quasi-bound states inside the well cause Fabry-Pérot-like constructive interference, yielding sharp transmission peaks far exceeding classical expectations.',
    hints: [
      'Two barriers are active! Observe how transmission varies non-monotonically with energy.',
      'As energy rises, resonant tunneling occurs when internal reflections constructively reinforce.',
      'Sweep particle energy toward E ≈ 0.80 to reach the 65% target window.',
    ],
    initialState: {
      particleEnergy: 0.30,
      barriers: [
        { id: 'b1', height: 1.20, width: 0.40, adjustableHeight: false, adjustableWidth: false },
        { id: 'b2', height: 1.20, width: 0.40, adjustableHeight: false, adjustableWidth: false },
      ],
    },
    targetState: { targetTransmission: 0.65, tolerance: 0.03 },
    tolerance: 0.03,
    tunnelingLevel: {
      id: 't4_l7',
      trackId: 'quantum-tunneling',
      trackNumber: 4,
      levelNumber: 7,
      title: 'Double Barrier Resonance',
      subtitle: 'Quantum Well Phase Interference',
      description: 'Find the resonant transmission window around 65% ± 3%.',
      difficulty: 'Advanced',
      educationalConcept: 'Resonant tunneling diodes (RTDs) exploit constructive interference between double barriers to allow rapid quantum conduction.',
      hints: [
        'Notice that T does not rise simply monotonically; internal cavity reflections create resonance.',
        'At E ≈ 0.80, constructive cavity interference yields T ≈ 65.5%.',
        'Target window is 62% to 68%.',
      ],
      initialState: {
        particleEnergy: 0.30,
        barriers: [
          { id: 'b1', height: 1.20, width: 0.40, adjustableHeight: false, adjustableWidth: false },
          { id: 'b2', height: 1.20, width: 0.40, adjustableHeight: false, adjustableWidth: false },
        ],
      },
      targetTransmission: 0.65,
      targetTolerance: 0.03,
      energyRange: { min: 0.20, max: 1.15 },
      adjustableEnergy: true,
    },
  },

  // LEVEL 8 — ASYMMETRIC BARRIERS (Group 8)
  {
    id: 't4_l8',
    trackId: 'quantum-tunneling',
    trackNumber: 4,
    levelNumber: 8,
    title: 'Asymmetric Heterostructure',
    subtitle: 'Coupled Asymmetric Quantum Wells',
    description: 'Real semiconductor devices utilize heterostructures with asymmetric barrier heights. Tune particle energy and the height of the second barrier to land on the 40% transmission target.',
    difficulty: 'Advanced',
    educationalConcept: 'Barrier asymmetry shifts the resonance energy and limits peak transmission, demonstrating how modern bandgap engineering controls electron tunneling currents.',
    hints: [
      'Barrier 1 is fixed at V1 = 1.00. Barrier 2 height is adjustable.',
      'Adjust particle energy and Barrier 2 height in tandem.',
      'Try E ≈ 0.35 and Barrier 2 Height ≈ 1.30 to reach 40% ± 2%.',
    ],
    initialState: {
      particleEnergy: 0.35,
      barriers: [
        { id: 'b1', height: 1.00, width: 0.50, adjustableHeight: false, adjustableWidth: false },
        { id: 'b2', height: 2.00, width: 0.40, minHeight: 0.8, maxHeight: 2.2, adjustableHeight: true, adjustableWidth: false },
      ],
    },
    targetState: { targetTransmission: 0.40, tolerance: 0.02 },
    tolerance: 0.02,
    tunnelingLevel: {
      id: 't4_l8',
      trackId: 'quantum-tunneling',
      trackNumber: 4,
      levelNumber: 8,
      title: 'Asymmetric Heterostructure',
      subtitle: 'Coupled Asymmetric Quantum Wells',
      description: 'Tune asymmetric barrier parameters to hit 40% ± 2% transmission.',
      difficulty: 'Advanced',
      educationalConcept: 'Heterostructure potential steps tailor quantum tunneling impedance and resonance width.',
      hints: [
        'Initial state yields only 28.3% transmission due to high second barrier.',
        'Lower Barrier 2 height toward 1.30 while keeping E around 0.35.',
        'Target window is 38% to 42%.',
      ],
      initialState: {
        particleEnergy: 0.35,
        barriers: [
          { id: 'b1', height: 1.00, width: 0.50, adjustableHeight: false, adjustableWidth: false },
          { id: 'b2', height: 2.00, width: 0.40, minHeight: 0.8, maxHeight: 2.2, adjustableHeight: true, adjustableWidth: false },
        ],
      },
      targetTransmission: 0.40,
      targetTolerance: 0.02,
      energyRange: { min: 0.20, max: 0.95 },
      adjustableEnergy: true,
    },
  },

  // LEVEL 9 — TRIPLE BARRIER ARRAY (Group 9)
  {
    id: 't4_l9',
    trackId: 'quantum-tunneling',
    trackNumber: 4,
    levelNumber: 9,
    title: 'Triple Barrier Superlattice',
    subtitle: 'Miniband Formation in Periodic Potentials',
    description: 'Three barriers define a dual-well superlattice. Multiple transmission peaks emerge corresponding to split energy levels. Adjust particle energy and central barrier width to reach the target transmission of 52%.',
    difficulty: 'Expert',
    educationalConcept: 'Periodic arrays of barriers cause discrete resonance states to split into minibands, the fundamental mechanism underlying semiconductor superlattices and quantum cascade lasers.',
    hints: [
      'Three potential barriers are now in series!',
      'Tune Particle Energy and the central barrier’s width.',
      'Set E ≈ 0.50 and central Barrier Width ≈ 0.35 to match the 52% target.',
    ],
    initialState: {
      particleEnergy: 0.35,
      barriers: [
        { id: 'b1', height: 1.10, width: 0.35, adjustableHeight: false, adjustableWidth: false },
        { id: 'b2', height: 1.10, width: 0.70, minWidth: 0.2, maxWidth: 0.8, adjustableHeight: false, adjustableWidth: true },
        { id: 'b3', height: 1.10, width: 0.35, adjustableHeight: false, adjustableWidth: false },
      ],
    },
    targetState: { targetTransmission: 0.52, tolerance: 0.02 },
    tolerance: 0.02,
    tunnelingLevel: {
      id: 't4_l9',
      trackId: 'quantum-tunneling',
      trackNumber: 4,
      levelNumber: 9,
      title: 'Triple Barrier Superlattice',
      subtitle: 'Miniband Formation in Periodic Potentials',
      description: 'Navigate triple-barrier miniband transmission to reach 52% ± 2%.',
      difficulty: 'Expert',
      educationalConcept: 'Periodic quantum potentials give rise to energy band structures through multi-barrier quantum coherence.',
      hints: [
        'Notice how the central barrier controls coupling between the two adjacent quantum wells.',
        'Slimming the central barrier increases inter-well coupling.',
        'Target configuration: E ≈ 0.50, central width a2 ≈ 0.35.',
      ],
      initialState: {
        particleEnergy: 0.35,
        barriers: [
          { id: 'b1', height: 1.10, width: 0.35, adjustableHeight: false, adjustableWidth: false },
          { id: 'b2', height: 1.10, width: 0.70, minWidth: 0.2, maxWidth: 0.8, adjustableHeight: false, adjustableWidth: true },
          { id: 'b3', height: 1.10, width: 0.35, adjustableHeight: false, adjustableWidth: false },
        ],
      },
      targetTransmission: 0.52,
      targetTolerance: 0.02,
      energyRange: { min: 0.25, max: 1.05 },
      adjustableEnergy: true,
    },
  },

  // LEVEL 10 — TUNNEL MASTER (Group 10: 4 Barriers, Timer, Move Constraint)
  {
    id: 't4_l10',
    trackId: 'quantum-tunneling',
    trackNumber: 4,
    levelNumber: 10,
    title: 'Tunnel Master',
    subtitle: 'The 4-Barrier Multi-Cavity Precision Gauntlet',
    description: 'The pinnacle challenge of Track 4: a 4-barrier multi-cavity potential landscape! You must coordinate particle energy, Barrier 1 width, and Barrier 4 height under a 75-second countdown to land precisely in the 78% ± 2% target zone.',
    difficulty: 'Expert',
    educationalConcept: 'Multi-barrier quantum engineering requires mastery over cumulative phase shifts, evanescent wave amplitudes, and multi-cavity transmission resonance.',
    hints: [
      'Four barriers form a complex coupled quantum landscape.',
      'Particle Energy, Barrier 1 Width, and Barrier 4 Height can all be adjusted.',
      'Target: E ≈ 0.90, Barrier 1 width ≈ 0.20, Barrier 4 height ≈ 1.00 yields T ≈ 77.8%.',
    ],
    initialState: {
      particleEnergy: 0.40,
      barriers: [
        { id: 'b1', height: 1.00, width: 0.50, minWidth: 0.20, maxWidth: 0.60, adjustableHeight: false, adjustableWidth: true },
        { id: 'b2', height: 1.20, width: 0.30, adjustableHeight: false, adjustableWidth: false },
        { id: 'b3', height: 1.20, width: 0.30, adjustableHeight: false, adjustableWidth: false },
        { id: 'b4', height: 1.40, width: 0.30, minHeight: 0.80, maxHeight: 1.50, adjustableHeight: true, adjustableWidth: false },
      ],
    },
    targetState: { targetTransmission: 0.78, tolerance: 0.02 },
    tolerance: 0.02,
    constraints: { maxMoves: 12 },
    tunnelingLevel: {
      id: 't4_l10',
      trackId: 'quantum-tunneling',
      trackNumber: 4,
      levelNumber: 10,
      title: 'Tunnel Master',
      subtitle: 'The 4-Barrier Multi-Cavity Precision Gauntlet',
      description: 'Master 4 barriers under 75 seconds to achieve 78% ± 2% transmission.',
      difficulty: 'Expert',
      educationalConcept: 'Full multi-barrier quantum coherence and precision parameter matching.',
      hints: [
        'Watch the countdown timer and your move limit.',
        'Raise particle energy close to 0.90 to drive high tunneling amplitude through the 4 barriers.',
        'Narrow Barrier 1 to 0.20 and lower Barrier 4 to 1.00 to hit the 76%–80% window.',
      ],
      initialState: {
        particleEnergy: 0.40,
        barriers: [
          { id: 'b1', height: 1.00, width: 0.50, minWidth: 0.20, maxWidth: 0.60, adjustableHeight: false, adjustableWidth: true },
          { id: 'b2', height: 1.20, width: 0.30, adjustableHeight: false, adjustableWidth: false },
          { id: 'b3', height: 1.20, width: 0.30, adjustableHeight: false, adjustableWidth: false },
          { id: 'b4', height: 1.40, width: 0.30, minHeight: 0.80, maxHeight: 1.50, adjustableHeight: true, adjustableWidth: false },
        ],
      },
      targetTransmission: 0.78,
      targetTolerance: 0.02,
      energyRange: { min: 0.30, max: 0.95 },
      adjustableEnergy: true,
      timeLimit: 75,
      allowedMoves: 12,
    },
  },
];
