// Track 5 — Quantum Spin & Measurement (Spin Splitter) Level Catalog
// 10 Calibrated levels teaching spin-1/2 Stern-Gerlach measurement, measurement axes,
// quantum probability distribution, state collapse, and sequential measurement disturbance.

import type { LevelDefinition } from '../types';
import {
  SpinSplitterLevelConfig,
  angleToAxis2D,
} from '../engines/spinSplitterEngine';

export interface SpinLevelConfig extends LevelDefinition, SpinSplitterLevelConfig {}

export const TRACK_5_LEVELS: SpinLevelConfig[] = [
  // LEVEL 1: MEET SPIN
  {
    id: 't5_l1',
    trackId: 'phase-estimation', // Preserving trackId route for Quantum Navigator
    trackNumber: 5,
    levelNumber: 1,
    title: 'Meet Quantum Spin',
    subtitle: 'Two Outcomes of a Spin-1/2 Particle',
    description: 'A collimated beam of spin-1/2 particles in state +Z enters the analyzer. Run the experiment to observe how the analyzer measures spin and deflects particles toward Detector +.',
    difficulty: 'Beginner',
    educationalConcept: 'A spin-1/2 measurement along an axis n produces exactly two discrete outcomes (+ and -). When the spin vector r is aligned with the analyzer axis n (θ = 0°), P(+) = cos²(0°) = 100%.',
    hints: [
      'The incoming particle beam has spin aligned along +Z (upward).',
      'The analyzer measurement axis is currently oriented along +Z (0°).',
      'Click "Run Experiment" to send 50 particles through the analyzer and record the detector counts.',
    ],
    initialState: { analyzer1Angle: 0, hasRunExperiment: false },
    targetState: { targetProbPlus: 1.0 },
    tolerance: 0.04,
    sourceState: angleToAxis2D(0), // +Z
    sourceName: '+Z (|0⟩)',
    analyzerCount: 1,
    analyzer1InitialAngle: 0,
    analyzer1Adjustable: true,
    targetProbPlus: 1.0,
    targetTolerance: 0.04,
    targetDetector: 'analyzer1',
    xpReward: 200,
    starThresholds: { threeStars: 150, fourStars: 200, fiveStars: 250 },
  },

  // LEVEL 2: ROTATE THE ANALYZER
  {
    id: 't5_l2',
    trackId: 'phase-estimation',
    trackNumber: 5,
    levelNumber: 2,
    title: 'Rotate the Analyzer',
    subtitle: 'The 50/50 Superposition Split (θ = 90°)',
    description: 'The incoming spin is +Z. Rotate the analyzer until it is perpendicular to the particle spin (+X at 90° or -X at 270°) to produce an equal 50/50 split across both detectors.',
    difficulty: 'Beginner',
    educationalConcept: 'Measuring a spin along an orthogonal axis creates equal superposition probabilities: P(+) = cos²(90°/2) = cos²(45°) = 50%, and P(-) = sin²(45°) = 50%.',
    hints: [
      'Drag the analyzer needle to rotate its measurement axis.',
      'To get a 50/50 split, the analyzer must be perpendicular (90° or 270°) to the incoming +Z spin.',
      'Set the orientation to 90° (+X) and run the experiment.',
    ],
    initialState: { analyzer1Angle: 0, hasRunExperiment: false },
    targetState: { targetProbPlus: 0.5 },
    tolerance: 0.03,
    sourceState: angleToAxis2D(0), // +Z
    sourceName: '+Z (|0⟩)',
    analyzerCount: 1,
    analyzer1InitialAngle: 0,
    analyzer1Adjustable: true,
    targetProbPlus: 0.5,
    targetTolerance: 0.03,
    targetDetector: 'analyzer1',
    xpReward: 250,
    starThresholds: { threeStars: 200, fourStars: 250, fiveStars: 300 },
  },

  // LEVEL 3: FIND 50/50 ON INCLINED SPIN
  {
    id: 't5_l3',
    trackId: 'phase-estimation',
    trackNumber: 5,
    levelNumber: 3,
    title: 'Orthogonal Measurement',
    subtitle: 'Perpendicular Axis to Inclined Spin (Source at 30°)',
    description: 'The particle source is tilted at angle 30°. Find an orientation perpendicular to the incoming spin (90° angular difference) to achieve a 50/50 detector split.',
    difficulty: 'Intermediate',
    educationalConcept: 'Quantum measurement probabilities depend purely on the relative angle θ between the spin vector r and analyzer axis n: P(+) = (1 + r · n) / 2.',
    hints: [
      'The source spin is oriented at 30° in the measurement plane.',
      'A 50/50 split requires r · n = 0, which means an angular separation of 90°.',
      'Rotate the analyzer to 30° + 90° = 120° (or 300°).',
    ],
    initialState: { analyzer1Angle: 30, hasRunExperiment: false },
    targetState: { targetProbPlus: 0.5 },
    tolerance: 0.03,
    sourceState: angleToAxis2D(30),
    sourceName: 'Tilted Spin (30°)',
    analyzerCount: 1,
    analyzer1InitialAngle: 30,
    analyzer1Adjustable: true,
    targetProbPlus: 0.5,
    targetTolerance: 0.03,
    targetDetector: 'analyzer1',
    xpReward: 300,
    starThresholds: { threeStars: 250, fourStars: 300, fiveStars: 350 },
  },

  // LEVEL 4: FIND THE 75/25 SPLIT
  {
    id: 't5_l4',
    trackId: 'phase-estimation',
    trackNumber: 5,
    levelNumber: 4,
    title: 'Find the 75/25 Split',
    subtitle: 'The Cosine-Squared Rule (θ = 60°)',
    description: 'The incoming spin is +Z. Rotate the analyzer to an angle that produces approximately 75% particles at Detector + and 25% at Detector -.',
    difficulty: 'Intermediate',
    educationalConcept: 'For a spin-1/2 particle, P(+) = cos²(θ/2). To obtain P(+) = 0.75, we need cos(θ/2) = √3/2, which gives θ/2 = 30° and thus θ = 60°.',
    hints: [
      'The formula is P(+) = cos²(θ/2).',
      'For P(+) = 75%, θ/2 must be 30°, which means θ = 60°.',
      'Rotate the analyzer from 0° to 60° (or 300°) and run the experiment.',
    ],
    initialState: { analyzer1Angle: 0, hasRunExperiment: false },
    targetState: { targetProbPlus: 0.75 },
    tolerance: 0.03,
    sourceState: angleToAxis2D(0), // +Z
    sourceName: '+Z (|0⟩)',
    analyzerCount: 1,
    analyzer1InitialAngle: 0,
    analyzer1Adjustable: true,
    targetProbPlus: 0.75,
    targetTolerance: 0.03,
    targetDetector: 'analyzer1',
    xpReward: 350,
    starThresholds: { threeStars: 300, fourStars: 350, fiveStars: 400 },
  },

  // LEVEL 5: OPPOSITE DIRECTION
  {
    id: 't5_l5',
    trackId: 'phase-estimation',
    trackNumber: 5,
    levelNumber: 5,
    title: 'Opposite Direction',
    subtitle: 'Complete Inversion to Detector - (θ = 180°)',
    description: 'The incoming spin is +Z. Orient the analyzer directly opposite to the incoming spin so that all particles are diverted into Detector -.',
    difficulty: 'Intermediate',
    educationalConcept: 'When the analyzer axis is anti-parallel to the spin vector (θ = 180°), r · n = -1. P(+) = cos²(90°) = 0%, and P(-) = sin²(90°) = 100%.',
    hints: [
      'The particle spin points upward (+Z at 0°).',
      'To deflect all particles to Detector -, orient the analyzer directly downward (-Z at 180°).',
      'Set the analyzer needle to 180° and click "Run Experiment".',
    ],
    initialState: { analyzer1Angle: 0, hasRunExperiment: false },
    targetState: { targetProbPlus: 0.0 },
    tolerance: 0.03,
    sourceState: angleToAxis2D(0), // +Z
    sourceName: '+Z (|0⟩)',
    analyzerCount: 1,
    analyzer1InitialAngle: 0,
    analyzer1Adjustable: true,
    targetProbPlus: 0.0,
    targetTolerance: 0.03,
    targetDetector: 'analyzer1',
    xpReward: 400,
    starThresholds: { threeStars: 350, fourStars: 400, fiveStars: 450 },
  },

  // LEVEL 6: PREPARE A STATE (SEQUENTIAL INTRODUCTION)
  {
    id: 't5_l6',
    trackId: 'phase-estimation',
    trackNumber: 5,
    levelNumber: 6,
    title: 'Prepare a State',
    subtitle: 'State Projection & Branch Selection',
    description: 'Sequential measurement begins! Analyzer 1 measures along +X (90°), collapsing particles into +X or -X. Select the + branch to channel the newly prepared +X state into Analyzer 2, then align Analyzer 2 at +X to verify 100% transmission.',
    difficulty: 'Advanced',
    educationalConcept: 'Von Neumann projection postulate: measuring along axis n projects the spin into state r\' = +n (if + outcome) or r\' = -n (if - outcome). The collapsed state can now be used as the input to a subsequent analyzer.',
    hints: [
      'Analyzer 1 is fixed at 90° (+X). It splits the +Z beam equally into +X and -X.',
      'Click the "+ Branch" button to select the beam emerging from the + outcome.',
      'Align Analyzer 2 to 90° (+X) so the measured +X state enters an aligned analyzer, giving 100% +.',
    ],
    initialState: { analyzer1Angle: 90, analyzer2Angle: 0, selectedBranch: '+', hasRunExperiment: false },
    targetState: { targetProbPlus: 1.0 },
    tolerance: 0.04,
    sourceState: angleToAxis2D(0), // +Z
    sourceName: '+Z (|0⟩)',
    analyzerCount: 2,
    analyzer1InitialAngle: 90,
    analyzer1Adjustable: false,
    analyzer2InitialAngle: 0,
    analyzer2Adjustable: true,
    branchSelectionRequired: true,
    targetBranch: '+',
    targetProbPlus: 1.0,
    targetTolerance: 0.04,
    targetDetector: 'analyzer2',
    xpReward: 450,
    starThresholds: { threeStars: 400, fourStars: 450, fiveStars: 500 },
  },

  // LEVEL 7: SECOND ANALYZER (MEASUREMENT DISTURBANCE)
  {
    id: 't5_l7',
    trackId: 'phase-estimation',
    trackNumber: 5,
    levelNumber: 7,
    title: 'Measurement Disturbance',
    subtitle: 'Erasing the Past State (+Z -> +X -> 50/50 at +Z)',
    description: 'The original beam was +Z. Analyzer 1 measured along +X and prepared a +X beam. Now rotate Analyzer 2 back to +Z (0°) to discover that the original +Z certainty was completely erased into a 50/50 split!',
    difficulty: 'Advanced',
    educationalConcept: 'Quantum measurement disturbance: measuring spin along X collapses the state to |+X⟩ = (|0⟩ + |1⟩)/√2. Subsequent measurement along Z yields a 50/50 split, proving measurement physically alters quantum systems.',
    hints: [
      'The particle entering Analyzer 2 is in state +X (90°).',
      'To produce a 50/50 split, Analyzer 2 must be perpendicular to +X.',
      'Rotate Analyzer 2 to 0° (+Z) or 180° (-Z) and run the experiment.',
    ],
    initialState: { analyzer1Angle: 90, analyzer2Angle: 90, selectedBranch: '+', hasRunExperiment: false },
    targetState: { targetProbPlus: 0.5 },
    tolerance: 0.03,
    sourceState: angleToAxis2D(0), // +Z
    sourceName: '+Z (|0⟩)',
    analyzerCount: 2,
    analyzer1InitialAngle: 90,
    analyzer1Adjustable: false,
    analyzer2InitialAngle: 90,
    analyzer2Adjustable: true,
    branchSelectionRequired: true,
    targetBranch: '+',
    targetProbPlus: 0.5,
    targetTolerance: 0.03,
    targetDetector: 'analyzer2',
    xpReward: 500,
    starThresholds: { threeStars: 450, fourStars: 500, fiveStars: 550 },
  },

  // LEVEL 8: SELECT THE BRANCH
  {
    id: 't5_l8',
    trackId: 'phase-estimation',
    trackNumber: 5,
    levelNumber: 8,
    title: 'Branch Steering',
    subtitle: '75/25 Split on Post-Measurement State',
    description: 'Analyzer 1 measures along +X (90°). Select the + branch (+X state). Then rotate Analyzer 2 to create a 75/25 split at Detector 2 (θ = 60° relative to +X).',
    difficulty: 'Expert',
    educationalConcept: 'Relative angle on sequential measurement: the state entering Analyzer 2 is +X (90°). For P(+) = 75%, Analyzer 2 must differ by 60°: either 90° - 60° = 30° or 90° + 60° = 150°.',
    hints: [
      'Ensure the + Branch is active (+X state entering Analyzer 2).',
      'The state entering Analyzer 2 has orientation 90°.',
      'To get 75% at Detector +, rotate Analyzer 2 to 90° - 60° = 30° (or 150°).',
    ],
    initialState: { analyzer1Angle: 90, analyzer2Angle: 0, selectedBranch: '+', hasRunExperiment: false },
    targetState: { targetProbPlus: 0.75 },
    tolerance: 0.03,
    sourceState: angleToAxis2D(0), // +Z
    sourceName: '+Z (|0⟩)',
    analyzerCount: 2,
    analyzer1InitialAngle: 90,
    analyzer1Adjustable: false,
    analyzer2InitialAngle: 0,
    analyzer2Adjustable: true,
    branchSelectionRequired: true,
    targetBranch: '+',
    targetProbPlus: 0.75,
    targetTolerance: 0.03,
    targetDetector: 'analyzer2',
    xpReward: 600,
    starThresholds: { threeStars: 550, fourStars: 600, fiveStars: 650 },
  },

  // LEVEL 9: EXPERIMENT CHALLENGE
  {
    id: 't5_l9',
    trackId: 'phase-estimation',
    trackNumber: 5,
    levelNumber: 9,
    title: 'Experiment Budget Challenge',
    subtitle: 'Limited Runs (3 Runs Max, Target: 75% ± 3%)',
    description: 'Resource management challenge: You have only 3 experimental runs and 45 seconds to configure Analyzer 1 and Analyzer 2 to produce a 75/25 detector split.',
    difficulty: 'Expert',
    educationalConcept: 'Experimental quantum physics requires designing apparatus orientations and conserving particle beam resources before committing to measurement.',
    hints: [
      'You only have 3 experiment runs! Calculate the angle before running.',
      'Analyzer 1 is at 0° (+Z). To get 75% at Analyzer 1, rotate Analyzer 1 to 60°.',
      'Alternatively, if using Analyzer 2, keep both aligned at 60° separation.',
    ],
    initialState: { analyzer1Angle: 0, analyzer2Angle: 0, selectedBranch: '+', hasRunExperiment: false, experimentsUsed: 0 },
    targetState: { targetProbPlus: 0.75 },
    tolerance: 0.03,
    sourceState: angleToAxis2D(0), // +Z
    sourceName: '+Z (|0⟩)',
    analyzerCount: 1,
    analyzer1InitialAngle: 0,
    analyzer1Adjustable: true,
    allowedExperiments: 3,
    timeLimit: 45,
    targetProbPlus: 0.75,
    targetTolerance: 0.03,
    targetDetector: 'analyzer1',
    xpReward: 750,
    starThresholds: { threeStars: 700, fourStars: 750, fiveStars: 850 },
  },

  // LEVEL 10: SPIN MASTER
  {
    id: 't5_l10',
    trackId: 'phase-estimation',
    trackNumber: 5,
    levelNumber: 10,
    title: 'Spin Master',
    subtitle: 'The Grand Final Track 5 Challenge (80% ± 3%)',
    description: 'The ultimate quantum spin challenge! Configure both analyzers and select the proper branch to prepare and measure an 80/20 detector distribution under strict time and experiment limits.',
    difficulty: 'Expert',
    educationalConcept: 'Mastery of quantum spin and Stern-Gerlach apparatus: coordinating state preparation, state projection, branch selection, and precision orientation to attain exact target statistics.',
    hints: [
      'Target is 80% + (cos²(θ/2) = 0.80 -> θ ≈ 53.1°).',
      'Set Analyzer 1 to 90° (+X), select the + Branch (+X state).',
      'Rotate Analyzer 2 to 90° - 53° = 37° (or 143°) to achieve 80% +.',
      'Run the experiment to claim the title of Quantum Spin Master!',
    ],
    initialState: { analyzer1Angle: 0, analyzer2Angle: 0, selectedBranch: '+', hasRunExperiment: false, experimentsUsed: 0 },
    targetState: { targetProbPlus: 0.80 },
    tolerance: 0.03,
    sourceState: angleToAxis2D(0), // +Z
    sourceName: '+Z (|0⟩)',
    analyzerCount: 2,
    analyzer1InitialAngle: 0,
    analyzer1Adjustable: true,
    analyzer2InitialAngle: 0,
    analyzer2Adjustable: true,
    branchSelectionRequired: true,
    targetBranch: '+',
    allowedExperiments: 3,
    timeLimit: 60,
    targetProbPlus: 0.80,
    targetTolerance: 0.03,
    targetDetector: 'analyzer2',
    xpReward: 1000,
    starThresholds: { threeStars: 900, fourStars: 1000, fiveStars: 1200 },
  },
];
